pipeline {
    agent any
    tools {
        maven '3.8.6'
    }
        stages{
            stage('Build'){
                 steps{
                    echo 'Hello Worldd'
                }
            }
            stage('Upload War To Nexus'){
                steps{
                nexusArtifactUploader artifacts: [
                    [
                        artifactId: 'my-app', 
                        classifier: '', 
                        file: 'C:\Users\apari\my-app\target\my-app-1.0-SNAPSHOT.jar', 
                        type: 'jar'
                        ]
                    ], 
                    credentialsId: 'nexuscredenciales', 
                    groupId: 'com.abstracta.app', 
                    nexusUrl: 'localhost:8081', 
                    nexusVersion: 'nexus3', 
                    protocol: 'http', 
                    repository: 'simpleapp-release', 
                    version: '1.0-SNAPSHOT'
            }
        }
    }
}
